# Used to trigger self-push CI
name: Self-hosted runner (push-caller)

on:
  pull_request:


jobs:
  check-for-setup:
      runs-on: ubuntu-22.04
      name: Check if setup was changed
      steps:
        - uses: actions/checkout@v4
          with: 
            fetch-depth: "2"
